version: '3'
services:
  sync-tasks-cronjob:
    build:
      context: .
      dockerfile: Dockerfile
    image: sync-tasks-cronjob:latest
    container_name: sync-tasks-cronjob-container
    environment:
      - PYTHONUNBUFFERED=1
