version: '3'
services:
  sync-tasks-cronjob:
    build:
      context: .
      dockerfile: Dockerfile
    image: sync-tasks-cronjob:latest
    container_name: sync-tasks-cronjob-container
    volumes:
      - ./config.prod.ini:/app/config.prod.ini
    environment:
      - PYTHONUNBUFFERED=1